### ISSUE TITLE
the demo  does not seem to have any contextual capability for chatgpt

### ISSUE THREAD

**Issue by wuimin** [MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator#21]
When I ask chatGPT a follow-up question, it doesn't seem to have the ability to maintain context. well, I understand that This should indeed be a feature of GPT, at least it should be able to remember a certain number of historical questions. 
for example: if I asked help to list 10 news websites, it worked well, when I asked "need more", it didn't know what shoud do at all.

**Comment by piizei** [comment]
Seems like bug in the cosmosdb history. If you look from database, there is ony ever 1 question and 1 answer on any conversation.

**Comment by piizei** [comment]
I actually got it working just fixing my partition-key in the cosmosdb container. It needs to be /user_id, otherwise it will lose the history.

**Comment by hwan18** [comment]
> I actually got it working just fixing my partition-key in the cosmosdb container. It needs to be /user_id, otherwise it will lose the history.

This helped me. To be exact you can find it here:
![image](https://github.com/MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator/assets/14958642/d6e4eceb-0e99-4b04-93b2-dcdd6de6dba8)

You can not edit it so you have to make a new container.

Hope this helps.

**Comment by wuimin** [comment]
sorry, I have little confused. by default, there's parttion key set as "user_id"
<img width="387" alt="image" src="https://github.com/MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator/assets/49023873/a6ab3175-9b3a-410d-ae24-1ac4777814ef">

**Comment by hwan18** [comment]
> sorry, I have little confused. by default, there's parttion key set as "user_id". anything else I need to modify? Thanks! <img alt="image" width="387" src="https://user-images.githubusercontent.com/49023873/282274035-a6ab3175-9b3a-410d-ae24-1ac4777814ef.png">

No, that's all you need.
