### ISSUE TITLE
There was an error sending this message to your bot: HTTP status code ServiceUnavailable 

### ISSUE THREAD

**Issue by carlaelisa** [MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator#27]
It seems that my backend is not deployed correctly altough was following the instuctions given. Any ideas why this might be? 

![image](https://github.com/MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator/assets/62431273/a933f9cb-1950-44aa-a96b-1ea193ec8014)

**Comment by joel-domingo** [comment]
Try turning on the HTTPS Only setting in the webapp configuration > General settings.

![image](https://github.com/MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator/assets/39328868/d8f1f8db-a357-433b-92a8-8d3d8bb38d2d)

**Comment by carlaelisa** [comment]
I did that but still its not working, 
However, i get now a different message 
![image](https://github.com/MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator/assets/62431273/5fbafc07-a986-4ad5-a312-f6ebdf078bcd)

**Comment by carlaelisa** [comment]
Thank you - that helped
