### ISSUE TITLE
How do I bring the CSVTabularTool in the frontend 

### ISSUE THREAD

**Issue by carlaelisa** [MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator#29]
I understand that in the demo it uses the sql connection to query of the tabular data. However, I'd like to include the CSVTabularTool as well. 

I did the following: 
- in the bot.py i included the following: 
        file_url = "testdata.csv"
        csv_search = CSVTabularTool(path=file_url, llm=llm, callback_manager=cb_manager, return_direct=True)
        
        and updated the tools list: 
        tools = [www_search,csv_search, sql_search, doc_search, chatgpt_search, book_search]

the corresponding testdata.csv i stored in the same folder structure. 

When i deployed this and try @csvfile then i have the following output:
![image](https://github.com/MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator/assets/62431273/a484c774-a1ee-4c02-8ba1-3193c3f5abb1)

**Comment by pablomarin** [comment]
What you did is correct, something is happening in your deployment that the code is not being updated. This would be my guess. But your steps are correct.

**Comment by carlaelisa** [comment]
Thank you @pablomarin for your response. It did not give me something back after several tries - So I ended up using sqlsearch again.
