### ISSUE TITLE
Where should I set the table_info parameter?

### ISSUE THREAD

**Issue by tyler-suard-parker** [MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator#33]
Hello.  In Prompts.py around line 294, there is a variable called table_info, for designating which tables the agent should search.  It is not obvious in your code where this variable should be set.

**Comment by pablomarin** [comment]
This is a variable that is dynamically populated by the langchain's sql agent. Refer to the langchain repo so you can understand how the agent works:

https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/agent_toolkits/sql/toolkit.py
https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/tools/sql_database/tool.py
