### ISSUE TITLE
High costs due to Azure Cognitiv Services

### ISSUE THREAD

**Issue by loetters** [MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator#4]
Hi,
initiating the demo in particular the search index of Azure Cognitive Search creates high costs in our case 1300 $.

There is no warning or note. In my eyes this is a no go and untrustworthy.

**Comment by pablomarin** [comment]
You are correct, we should put a warning . Thank you for bringing it up.

**Comment by loetters** [comment]
Thats great. Waiting to get a refund from you or Microsoft, please contact me.

**Comment by pablomarin** [comment]
Please contact Microsoft Azure support for these kind of questions

**Comment by KonTheCat** [comment]
+1 this needs a clear warning please!

**Comment by carlaelisa** [comment]
Hello, 
We have this Accelerator and connected to our own data. The performance is satisfying although we experience very high costs. we did some testing (around 20 prompts) and we paid 30 dollar for Azure OpenAI alone. This is extremely expensive. 
is there any way to lower the costs of this solution?
