### ISSUE TITLE
Notebook 11. ValueError: An output parsing error occurred. 

### ISSUE THREAD

**Issue by vykhand** [MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator#57]
Hey folks, I keep getting parsing errors for the csv agent in Notebook 11, despite setting the model to gpt4 and adding the handling_parsing_errors=True parameter in the utils.py:451

It is probably related to some regression in the langchain, I wasn't able to pin the root cause yet. 

```

ValueError: An output parsing error occurred. In order to pass this error back to the agent and have it try again, pass `handle_parsing_errors=True` to the AgentExecutor. This is the error: Could not parse tool input: {'arguments': "import pandas as pd\n\ndf = pd.read_csv('covid_data.csv')\nrows = df.shape[0]\nrows", 'name': 'python'} because the `arguments` is not valid JSON.

```

**Comment by pablomarin** [comment]
make sure you have the model version 1106 or 0125 of gpt3.5 turbo or gpt4 turbo

**Comment by vykhand** [comment]
I tried all of those with no luck

**Comment by pablomarin** [comment]
If Notebook 7 works correctly, hence Notebook 11 should as well. Check you have the latest code.
