### ISSUE TITLE
cannot import name 'update_vector_indexes' from 'utils

### ISSUE THREAD

**Issue by wuimin** [MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator#58]
when I build the frontend web app with the latest repo, with the search page, I got the following error:
ImportError: cannot import name 'update_vector_indexes' from 'utils' (/tmp/8dc4360446125ac/utils.py)
could someone know what's the issue?

**Comment by pablomarin** [comment]
This is fixed on latest version
