### ISSUE TITLE
I can get the correct result with the Notebook 6(the first RAG), but there's error with the web search page

### ISSUE THREAD

**Issue by wuimin** [MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator#59]
I can get the correct result with the Notebook 6(the first RAG), everything is good.
but from the web search page, I always got the error:

Not data returned from Azure Search, check connection..

'value'

anyone got the same issue?

**Comment by pablomarin** [comment]
Hard to say what the error is, but normally a 'value' error happens when the search engine doesn't return any results. Check that.
