### ISSUE TITLE
06-SQLDB_QA broken: SQLDatabaseChain moved to langchain_experimental

### ISSUE THREAD

**Issue by adhazel** [MSUSAzureAccelerators/Azure-Cognitive-Search-Azure-OpenAI-Accelerator#7]
Based on [https://github.com/langchain-ai/langchain/blob/master/MIGRATE.md](https://github.com/langchain-ai/langchain/blob/master/MIGRATE.md), SQLDatabaseChain has been moved to langchain_experimental.

**Comment by pablomarin** [comment]
SQLDatabaseChain was removed from the notebook in our latest repo version.  Agents is the right way to do it.
